#impl.auth.interceptor=authorizationInterceptor
impl.auth.interceptor=authorizationAnnotationInterceptor

expire.session.pc=${expire.session}
expire.session.wap=5
expire.session.app=2880
expire.cookie=720

auth.name=ducati
auth.center=${auth.center}
